<a href="https://colab.research.google.com/github/RAJAS-KAR/-mongo/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [15]:
print(np._version)
print(np.show_config())

<module 'numpy._version' from '/usr/local/lib/python3.7/dist-packages/numpy/_version.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported 

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [16]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [17]:
np.size

<function numpy.size(a, axis=None)>

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [7]:
%run python -c ;"import numpy; numpy.info(numpy.add)"

ERROR:root:File `'python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [8]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
x = np.arange(50)
x = x[::-1]
print(x)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
y = np.arange(9).reshape(3,3)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [12]:
n = np.nonzero([1,2,0,0,4,0])
print(n)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [13]:
n = np.eye(3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [14]:
m = np.random.random((3,3,3))
print(m)

[[[0.43849911 0.39079777 0.04735018]
  [0.74580369 0.09421833 0.28858677]
  [0.57961473 0.98570997 0.11410445]]

 [[0.49524948 0.88021942 0.20309248]
  [0.08168993 0.79639017 0.35433786]
  [0.98625613 0.41428634 0.80300456]]

 [[0.67252897 0.9095655  0.85063948]
  [0.80654897 0.56801734 0.12031958]
  [0.28303188 0.28060406 0.3129217 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [15]:
s = np.random.random((10,10))
print(s.min(), s.max())

0.002596998451208088 0.9909168792697314


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [16]:
a = np.random.random(30)
a = a.mean()
print(a)

0.42854678263897317


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [17]:
s = np.ones((6,6))
s[1:-1,1:-1] = 0
print(s)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [18]:
a =np.ones((3,3))
print(np.pad(a,pad_width=1, mode='constant',constant_values=0))

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
print(0.3 == 3 * 0.1)
```

In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [20]:
print(np.diag(1+np.arange(4),k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [21]:
a = np.zeros((8,8),dtype = int)
a[1::2,::2]=1
a[::2,1::2]=1
print(a)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [22]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [23]:
a = np.tile(np.array([[0,1],[1,0]]),[2,3])
print(a)

[[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [18]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.28215193  1.04956553 -0.0965561   1.08520476  0.12240946]
 [-0.53928014 -0.97195273 -1.06107571  0.54587555 -1.34565887]
 [ 0.40653518  1.57609218 -1.12727137 -0.56801421 -0.70094231]
 [-0.76995938  0.53621007 -0.72585645 -0.70008072  0.2713103 ]
 [ 1.77547235  1.84217383 -1.19015483  1.67954175 -0.81143621]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [31]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [34]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [50]:
z = np.arange(11)
z[(z >= 3) & (z <= 8)] = -1
print(z)


[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [52]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [23]:
Z = np.arange(3)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [57]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [10]:
b = np.random.uniform(-20, +15, 10 )
print(np.copysign(np.ceil(np.abs(b)), b))

[  2. -11. -20.  11.   6.  -6.  12. -17.  -6. -10.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [16]:
x = np.random.randint(0,7,10)
y = np.random.randint(0,5,15)
print(np.intersect1d(x,y))

[0 1 2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [25]:
df = np.random.random(1000).reshape(10,10,10) * np.nan
np.seterr(all='ignore')
np.nanmedian(df, axis=[1, 2])

/usr/local/lib/python3.7/dist-packages/numpy/lib/nanfunctions.py:1120: RuntimeWarning: All-NaN slice encountered
  overwrite_input=overwrite_input)


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [26]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [29]:
yesterday = np.datetime64("today") - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64("today") + np.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [36]:
df = np.arange("2016-07", '2016-08', dtype = 'datetime64[D]')
print(df)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [50]:
a = np.ones(3)*1
b = np.ones(3)*2
np.add(a,b, out = b)
np.divide(a,2, out =a)
np.negative(a,out=a)
np.multiply(a,b,out=a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [59]:
df = np.random.uniform(0,10,10)
print(df - df%1)
print(np.floor(df))
print(np.ceil(df))
print(df.astype(int))
print(np.trunc(df))

[5. 8. 6. 6. 0. 1. 8. 4. 3. 7.]
[5. 8. 6. 6. 0. 1. 8. 4. 3. 7.]
[6. 9. 7. 7. 1. 2. 9. 5. 4. 8.]
[5 8 6 6 0 1 8 4 3 7]
[5. 8. 6. 6. 0. 1. 8. 4. 3. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [60]:
df = np.zeros((5,5))
df += np.arange(5)
print(df)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [63]:
def generate():
  for i in range(10):
    yield i
z = np.fromiter(generate(),dtype=float,count=-1)
print(z)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [67]:

Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [66]:
df = np.random.random(10)
df.sort()
print(df)

[0.02030913 0.07165773 0.11971795 0.18802059 0.41721462 0.48298552
 0.50326258 0.75946291 0.78004459 0.78795627]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [68]:
df = np.arange(10)
np.add.reduce(df)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [73]:
a = np.random.randint(0,4,5)
b = np.random.randint(0,4,5)
c = np.allclose(a,b)
print(c)
d = np.array_equal(a,b)
print(d)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [81]:
a = np.random.random((10,2))
b,c = a[:,0],a[:,1]
d = np.sqrt(b**2+c**2)
e = np.arctan2(c,b)
print(d)
print(e)

[1.00925313 0.54742594 0.95199522 0.62446746 0.71963778 0.84631678
 1.08331198 0.90787288 0.56736345 0.73859734]
[1.00761787 0.02938872 0.72287658 0.10260349 0.68621758 0.80253862
 1.15919285 0.15712543 0.67771465 0.31667016]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [84]:
s = np.random.random(10)
s[s.argmax()] = 0
print(s)

[0.         0.02358957 0.69974722 0.56433609 0.17208983 0.01257348
 0.36183585 0.56571927 0.30906377 0.86822065]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [25]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [26]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [90]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [91]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((40,40))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [4]:
a = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a[index])

98


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [5]:
a = np.zeros(10,[('position',[('x', float,1),('y', float, 1)]),
                 ('color',[('r', float,1),('g',float,1),('b',float,1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [10]:
a = np.random.random((10,2))
x,y = np.atleast_2d(a[:,0],a[:,1])
d = np.sqrt((x-x.T)**2 + (y-y.T))
print(d)

[[0.         1.16360116 0.96160454 0.91439525 0.64552044 0.59825043
  1.01550491 0.1442258  0.78346608 0.39326662]
 [       nan 0.                nan        nan 0.64350915 0.68614222
         nan 0.21519742 0.77612661        nan]
 [       nan 0.51209418 0.                nan 0.68206224 0.70982651
         nan 0.30499885 0.80923465        nan]
 [0.27061614 0.5947765  0.30362253 0.         0.74919115 0.77480437
         nan 0.43496849 0.86655024        nan]
 [       nan 1.01346161 0.76463034 0.70454182 0.                nan
  0.84256689        nan 0.44464708        nan]
 [       nan 1.10781548 0.87565284 0.82394003 0.27747774 0.
  0.95794242        nan 0.5248922         nan]
 [0.63858618 0.64140531 0.43942377 0.31618385 0.95616674 0.98920472
  0.         0.74047705 1.04973418        nan]
 [       nan 1.20642479 1.00430344 0.95939556 0.63117892 0.57389558
  1.06776441 0.         0.77220089 0.44020851]
 [       nan 0.90554555 0.61559011 0.53911124        nan        nan
  0.70869302        

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [11]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[14  7 70 86 76 87 62 84 45 31]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [27]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [38]:
 x = np.arange(12).reshape(3,4)
 for index, value in np.ndenumerate(x):
   print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(1, 3) 7
(2, 0) 8
(2, 1) 9
(2, 2) 10
(2, 3) 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [41]:
x,y =np.meshgrid(np.linspace(-1,-1,10),np.linspace(-1,-1,10))
z = np.sqrt(x*x+y*y)
sigma, mu = 1.0,0.0
g = np.exp(-((z-mu)**2/(2.0* sigma**2)))
print(g)

[[0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944 0.36787944 0.36787944 0.36787944]
 [0.36787944 0.36787944 0.36787944 0.36787944 0.36787944 0.36787944
  0.36787944

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [46]:
n = 5
p = 3
x = np.zeros((n,n),dtype=bool)
np.put(x,np.random.choice(range(n*n), p, replace=False),1)


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [49]:
a = np.random .rand(3,4)
print(a)
b = a-a.mean(axis=1,keepdims = True)
print(b)

[[0.83473689 0.43844704 0.05110608 0.99379767]
 [0.53895503 0.29407652 0.5412044  0.88017615]
 [0.1493265  0.47358118 0.07087744 0.03596268]]
[[ 0.25521497 -0.14107488 -0.52841584  0.41427575]
 [-0.024648   -0.2695265  -0.02239862  0.31657312]
 [-0.03311045  0.29114423 -0.11155951 -0.14647427]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [51]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[5 6 4]
 [3 5 0]
 [8 9 0]]
[[3 5 0]
 [5 6 4]
 [8 9 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [55]:
z = np.random.randint(0,3,(4,10))
print(z)
print((~Z.any(axis=0)).any())

[[1 0 2 1 1 1 1 1 2 0]
 [1 2 1 2 1 0 1 2 1 0]
 [1 1 1 1 1 2 2 0 2 2]
 [1 0 1 0 2 2 1 0 2 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [57]:
x = np.random.uniform(1,12,5)
y =4
z = x.flat[np.abs(x-y).argmin()]
print(z)

3.2973725582392226


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [63]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
print(it)
for x,y,z in it:
   z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [66]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [4]:
z = np.ones(10)
y = np.random.randint(0,len(z),20)
z += np.bincount(y,minlength=len(z))
print(z) 

[3. 2. 4. 1. 2. 4. 5. 4. 4. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [8]:
 X = [1,2,3,4,5,6]
 I = [1,3,9,3,4,1]
 F = np.bincount(I,X)
 print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [4]:
 w,h = 256,256
 x =np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
 colors = np.unique(x.reshape(-1,3), axis=0)
 y = len(colors)
 print(y)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [7]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)

[[62 47 50 53]
 [43 54 42 54]
 [52 56 60 57]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [28]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.64140808 0.49019967 0.40325477 0.49970301 0.50532811 0.53256077
 0.45331367 0.43085955 0.48289068 0.46152366]
0    0.641408
1    0.490200
2    0.403255
3    0.499703
4    0.505328
5    0.532561
6    0.453314
7    0.430860
8    0.482891
9    0.461524
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [14]:
x = np.random.uniform(0,1,(5,5))
y = np.random.uniform(0,1,(5,5)) 
np.diag(np.dot(x,y))

array([1.57108296, 1.13514689, 0.70357735, 1.21057155, 0.7671941 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [21]:
x = np.array([1,2,3,4,5])
y = 3
Z0 = np.zeros(len(x) + (len(x)-1)*(y))
Z0[::y+1] = x
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# #### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [32]:
a = np.ones((5,5,3))
b = np.ones((5,5))
print(a * b[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [33]:
a = np.arange(25).reshape(5,5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [36]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 9, 86) ( 9, 89) (14, 52) (14, 87) (14, 89) (14, 98) (15, 28) (15, 62)
 (16, 60) (16, 83) (22, 75) (22, 89) (27, 35) (27, 63) (28, 62) (32, 68)
 (32, 80) (35, 63) (37, 61) (37, 62) (52, 89) (57, 66) (57, 99) (60, 83)
 (61, 62) (66, 99) (68, 80) (75, 89) (86, 89) (87, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [44]:
c = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(c)),c)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [45]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [46]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [49]:
x = np.random.randint(0,2,100)
np.logical_not(x, out=x)
x = np.random.uniform(-1.0,1.0,100)
np.negative(x, out=x)

array([-0.9157897 ,  0.01512374, -0.57830095,  0.75980247, -0.1779853 ,
       -0.60660532, -0.63233112,  0.58963869,  0.70920649, -0.49223161,
        0.25506807,  0.06860495,  0.03394097, -0.44796713,  0.4788344 ,
        0.17679458,  0.84651217, -0.31692232,  0.32620857,  0.8933805 ,
       -0.7519697 , -0.78933208, -0.63602815,  0.79312578,  0.30704921,
        0.07120278,  0.63582435, -0.30543114,  0.2700444 ,  0.25523295,
        0.49039358,  0.72364325,  0.04632429,  0.29414225, -0.03499863,
        0.22529563, -0.40606864,  0.49843923,  0.24201237, -0.40577452,
        0.18790849, -0.05022437, -0.22757429, -0.15618483,  0.06718797,
        0.83663158,  0.42174358,  0.02979872, -0.16819025,  0.95763559,
       -0.93697541,  0.46037363, -0.99696134,  0.21748531, -0.9303927 ,
        0.40123083, -0.70783419,  0.52765198, -0.660462  ,  0.73934181,
        0.65381594, -0.67227428,  0.37627614, -0.59084338, -0.09352269,
       -0.09293934,  0.93347471, -0.81129248, -0.32431011, -0.02

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [59]:
def distance(P0, P1, p):
    x = P1 - P0
    y = (x**2).sum(axis=1)
    z = -((P0[:,0]-p[...,0])*x[:,0] + (P0[:,1]-p[...,1])*x[:,1]) / y
    z = z.reshape(len(z),1)
    l = P0 + z*x - p
    return np.sqrt((l**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.17951244  5.61974874  8.37535766 11.43364068  8.37431474  8.92775471
  5.20171621  6.34557875  8.13209393  3.85161682]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [60]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 7.01308845 12.43424822  1.72757274  2.32547005  7.82443572  0.50271908
   3.13809969  0.74053667  8.47815273  3.49508079]
 [ 7.41269402 15.62960145  4.93293752  2.7189772   5.04488917  4.07727226
   5.81898007  2.90860326  6.02823936  5.92794577]
 [ 6.24516051  8.38418731  2.25086499 10.94084692  3.86207494  0.03407284
  15.12640871 13.88993287  4.10840156  4.61642181]
 [ 2.4870866   4.13448104  6.57513649  2.18901266 10.88382934  7.67089067
   0.38333107  0.54241972 10.54943198  4.19946238]
 [ 3.2612001  15.51538992  4.88884787  7.96790473  7.56991819  7.34510364
  18.58505725 16.12025826  7.00146921  1.63801461]
 [10.58762336  3.17410514 13.82621687 15.26483942  2.73678021 11.97303497
   8.92460343  9.65920223  1.18854099 14.55888486]
 [11.78268109 16.97087695  6.25063081  7.09161041  8.89034766  4.23910232
   1.87386208  1.42020302 10.17098236  8.60606365]
 [ 1.92854442  3.2106028   7.47347783  6.60820765  6.55858757  7.33462231
   4.79670005  4.19157221  5.96626431  6.5983625 ]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [61]:

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 2 7 7 2 8 3 9 1 8]
 [7 0 5 3 3 0 3 4 6 0]
 [5 5 0 4 4 0 5 7 6 6]
 [3 9 1 9 5 9 7 5 8 9]
 [0 6 3 6 5 0 5 3 4 8]
 [5 5 2 5 9 8 2 9 5 3]
 [2 2 8 5 8 0 0 2 1 1]
 [6 1 0 7 6 3 6 1 4 4]
 [8 2 8 3 5 0 0 5 3 6]
 [0 7 4 5 7 6 5 0 0 1]]
[[0 0 0 0 0]
 [0 8 2 7 7]
 [0 7 0 5 3]
 [0 5 5 0 4]
 [0 3 9 1 9]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [70]:
x = np.arange(1,15,dtype=np.uint32)
y =stride_tricks.as_strided(x,(11,4),(4,4))
print(y)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [73]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)


10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [82]:
a = np.random.randint(0,10,30)
print(a)
print(np.bincount(a).argmax())

[7 1 7 2 0 8 6 5 2 4 5 6 1 6 5 8 0 0 7 8 6 8 8 2 7 1 6 6 3 0]
6


In [85]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 4 1]
   [2 3 0]
   [0 2 3]]

  [[4 1 4]
   [3 0 0]
   [2 3 3]]

  [[1 4 1]
   [0 0 2]
   [3 3 3]]

  [[4 1 4]
   [0 2 2]
   [3 3 1]]

  [[1 4 2]
   [2 2 4]
   [3 1 1]]

  [[4 2 1]
   [2 4 4]
   [1 1 0]]

  [[2 1 3]
   [4 4 3]
   [1 0 0]]

  [[1 3 3]
   [4 3 2]
   [0 0 0]]]


 [[[2 3 0]
   [0 2 3]
   [1 0 0]]

  [[3 0 0]
   [2 3 3]
   [0 0 0]]

  [[0 0 2]
   [3 3 3]
   [0 0 4]]

  [[0 2 2]
   [3 3 1]
   [0 4 1]]

  [[2 2 4]
   [3 1 1]
   [4 1 1]]

  [[2 4 4]
   [1 1 0]
   [1 1 0]]

  [[4 4 3]
   [1 0 0]
   [1 0 3]]

  [[4 3 2]
   [0 0 0]
   [0 3 2]]]


 [[[0 2 3]
   [1 0 0]
   [4 4 3]]

  [[2 3 3]
   [0 0 0]
   [4 3 4]]

  [[3 3 3]
   [0 0 4]
   [3 4 2]]

  [[3 3 1]
   [0 4 1]
   [4 2 0]]

  [[3 1 1]
   [4 1 1]
   [2 0 2]]

  [[1 1 0]
   [1 1 0]
   [0 2 4]]

  [[1 0 0]
   [1 0 3]
   [2 4 2]]

  [[0 0 0]
   [0 3 2]
   [4 2 4]]]


 [[[1 0 0]
   [4 4 3]
   [4 1 1]]

  [[0 0 0]
   [4 3 4]
   [1 1 2]]

  [[0 0 4]
   [3 4 2]
   [1 2 4]]

  [[0 4 1]
   [4 2 0]
   [2 4 1]]

  [[4 1 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [86]:

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  8 10 11 10]
 [ 8  4 10 13 16]
 [10 10  0 42  6]
 [11 13 42  7 15]
 [10 16  6 15  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [90]:
p,n = 5,10,
m = np.ones((p,n,n))
n = np.ones((p,n,1))
s = np.tensordot(m, n, axes =[[0,2],[0,1]])
print(s)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [93]:
a = np.ones((16,16))
b = 4
d = np.add.reduceat(np.add.reduceat(a,np.arange(0,a.shape[0], b),axis = 0),
                    np.arange(0, a.shape[1],b),axis =1)
print(s)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [3]:
def iterate(Z):
    
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [5]:
x = np.arange(500)
n =7
np.random.shuffle(x)

print(x[np.argpartition(-x,n)[:n]])

[495 496 494 499 497 498 493]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [12]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(y) for y in arrays)

    x = np.indices(shape, dtype=int)
    x = x.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
      x[:, n] = arrays[n][x[:, n]]

    return x

print (cartesian(([10, 20, 30], [40, 50], [60, 70])))

[[10 40 60]
 [10 40 70]
 [10 50 60]
 [10 50 70]
 [20 40 60]
 [20 40 70]
 [20 50 60]
 [20 50 70]
 [30 40 60]
 [30 40 70]
 [30 50 60]
 [30 50 70]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [19]:
a = np.array([("Raja",88.5,90),
              ("ram",87,99),
              ("RAJ",88.5,91)])
x = np.core.records.fromarrays(a.T,
                               names ="col1,col2,col3",
                               formats = "S80, f8, i8")
print(x)

[(b'Raja', 88.5, 90) (b'ram', 87. , 99) (b'RAJ', 88.5, 91)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [20]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.77 s ± 16.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
151 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
130 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [24]:

A = np.random.randint(0,7,(9,3))
B = np.random.randint(0,7,(3,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 4 8]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [27]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 0]
 [4 3 4]
 [2 3 4]
 [2 4 2]
 [4 3 4]
 [1 0 1]
 [0 2 1]
 [4 4 3]
 [4 1 1]
 [3 1 4]]
[[2 0 0]
 [4 3 4]
 [2 3 4]
 [2 4 2]
 [4 3 4]
 [1 0 1]
 [0 2 1]
 [4 4 3]
 [4 1 1]
 [3 1 4]]
[[2 0 0]
 [4 3 4]
 [2 3 4]
 [2 4 2]
 [4 3 4]
 [1 0 1]
 [0 2 1]
 [4 4 3]
 [4 1 1]
 [3 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [3]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,3,(5,2))
uZ = np.unique(Z, axis=0)
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)     #SUM  
np.einsum('i,i->i', A, B) #MUL
np.einsum('i,i', A, B)    #INNER
np.einsum('i,j->ij', A, B)   #OUTER

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [12]:

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
x = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
z = np.logical_and.reduce(np.mod(x, 1) ==0, axis=-1)
z &=(x.sum(axis=-1) == n)
print(x[z])




#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)